error handling

diff --git a/time-machine b/time-machine
--- a/time-machine
+++ b/time-machine
@@ -1,6 +1,6 @@
 #!/bin/bash
 # https://github.com/murkl/time-machine
-version=2.0.4
+version=2.0.3
 
 github_author=murkl
 github_repo=time-machine
@@ -116,6 +116,10 @@ check_for_update() {
         return 0
     fi
     latest_version=$(curl --silent "https://api.github.com/repos/$github_author/$github_repo/tags" | jq -r '.[0].name')
+    if [ "$latest_version" = "" ]; then
+        log "GitHub connection error"
+        exit 1
+    fi
     if [ "$version" = "$latest_version" ]; then
         log "No update available. (latest $script_id version: $latest_version)"
         return 0
@@ -188,6 +192,10 @@ show_update_gui() {
     rm -f "$tmp_file"
     ( curl --silent "https://api.github.com/repos/$github_author/$github_repo/tags" | jq -r '.[0].name' > "$tmp_file" )| zenity --progress --text="Fetching latest $script_id version" --pulsate --auto-close
     latest_version=$(< "$tmp_file")
+    if [ "$latest_version" = "" ]; then
+        send_notify "GitHub connection error"
+        return 1
+    fi
 
     version_info_text="No update available!\n\nForce install update <b>$latest_version</b>?"
     if [ "$version" != "$latest_version" ]; then
@@ -313,7 +321,7 @@ remove_desktop_file() {
     return 0
 }
 
-check_for_update &
+(check_for_update || send_notify "New $script_id update available") &
 
 # Main
 while(true); do
